- name: install microk8s native
  community.general.snap:
    name:
      - microk8s
    classic: true
    channel: "1.32"

- name: enable fw-rules for cni-networking
  ansible.builtin.shell:
    cmd: ufw allow in on cni0 && ufw allow out on cni0; ufw default allow routed

- name: show status
  ansible.builtin.shell:
    cmd: microk8s status --wait-ready
  register: out

- debug: var=out.stdout_lines


# cmd: ufw allow in on cni0 && ufw allow out on cni0; ufw default allow routed
