- name: install microk8s native
  community.general.snap:
    name:
      - microk8s
    classic: true
    channel: "{{ channel_version }}"

- name: enable ufw-rules for cni-networking
  ansible.builtin.shell:
    cmd: sudo ufw allow in on cni0 && sudo ufw allow out on cni0 && sudo ufw default allow routed

- name: Add the user to group microk8s
  ansible.builtin.user:
    name: "{{ ansible_ssh_user }}"
    group: microk8s

- name: create ~/.kube directory
  ansible.builtin.file:
    path: "{{ lookup('env','HOME') }}/.kube"
    state: directory
    recurse: yes
    owner: "{{ ansible_ssh_user }}"

- name: show status
  ansible.builtin.shell:
    cmd: microk8s status --wait-ready
  register: out

- debug: var=out.stdout_lines
